<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <Nullable>enable</Nullable>
    <!-- Not include this dll, only native dlls. -->
    <IncludeBuildOutput>false</IncludeBuildOutput>
    <IncludeContentInPack>true</IncludeContentInPack>
    <NoWarn>$(NoWarn);NU5100;NU5128</NoWarn>
    <Description>LZ4 native runtime for ios-arm64.</Description>

    <!-- NuGet -->
    <IsPackable>true</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="runtimes\**" />
    <None Include="runtimes\ios-arm64\native\liblz4.a" PackagePath="runtimes\ios-arm64\native\" Pack="true">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <!-- Normally Catalyst fallback to iOS, but this package must not fall back to this package's iOS static archive. Use dummy files instead. -->
    <None Update="packaging/_._" Pack="true" PackagePath="runtimes/maccatalyst-arm64/native/_._;runtimes/maccatalyst-x64/native/_._" />
  </ItemGroup>

</Project>
