<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-maccatalyst</TargetFramework>
    <SupportedOSPlatformVersion>15.0</SupportedOSPlatformVersion>
    <IsPackable>true</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="NativeCompressions.LZ4" Version="$(PackageVersion)" />
    <PackageReference Include="NativeCompressions.Zstandard" Version="$(PackageVersion)" />
  </ItemGroup>
</Project>
