<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <Nullable>enable</Nullable>
    <!-- Not include this dll, only native dlls. -->
    <IncludeBuildOutput>false</IncludeBuildOutput>
    <IncludeContentInPack>true</IncludeContentInPack>
    <NoWarn>$(NoWarn);NU5100;NU5128</NoWarn>
    <Description>OpenZL native runtimes for NativeCompressions.OpenZL.</Description>

    <!-- NuGet -->
    <IsPackable>true</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="runtimes\**" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="NativeCompressions.OpenZL.Runtime.linux-arm64.csproj" />
    <ProjectReference Include="NativeCompressions.OpenZL.Runtime.linux-x64.csproj" />
    <ProjectReference Include="NativeCompressions.OpenZL.Runtime.osx-arm64.csproj" />
    <ProjectReference Include="NativeCompressions.OpenZL.Runtime.osx-x64.csproj" />
    <ProjectReference Include="NativeCompressions.OpenZL.Runtime.win-arm64.csproj" />
    <ProjectReference Include="NativeCompressions.OpenZL.Runtime.win-x64.csproj" />
    <!-- Currently OpenZL android-arm can't build so remove it. -->
    <!--<ProjectReference Include="NativeCompressions.OpenZL.Runtime.android-arm.csproj" />-->
    <ProjectReference Include="NativeCompressions.OpenZL.Runtime.android-arm64.csproj" />
    <ProjectReference Include="NativeCompressions.OpenZL.Runtime.android-x64.csproj" />
    <ProjectReference Include="NativeCompressions.OpenZL.Runtime.ios-arm64.csproj" />
    <ProjectReference Include="NativeCompressions.OpenZL.Runtime.ios-x64.csproj" />
  </ItemGroup>

</Project>
