name: Build-iOS-Android

# on: workflow_dispatch
# for testing
on:
  push:
    branches:
      - feature/android-ios-build

jobs:
  # liblz4-ios-x64:
  #   runs-on: macos-latest
  #   timeout-minutes: 30
  #   defaults:
  #     run:
  #       working-directory: ./src/liblz4
  #   steps:
  #     - uses: actions/checkout@v3
  #       with:
  #         submodules: 'true'
  #     - run: rustup target add x86_64-apple-ios
  #     - run: cargo build --target x86_64-apple-ios --release
  #     # - uses: actions/upload-artifact@v3
  #     #   with:
  #     #     name: osx-x64
  #     #     path: ./src/libmagicphysx/target/x86_64-apple-darwin/release/libmagicphysx.dylib

  # liblz4-osx-arm64:
  #   runs-on: macos-latest
  #   timeout-minutes: 30
  #   defaults:
  #     run:
  #       working-directory: ./src/liblz4
  #   steps:
  #     - uses: actions/checkout@v3
  #       with:
  #         submodules: 'true'
  #     - run: rustup target add aarch64-apple-ios
  #     - run: cargo build --target aarch64-apple-ios --release
  #     # - uses: actions/upload-artifact@v3
  #     #   with:
  #     #     name: osx-arm64
  #     #     path: ./src/libmagicphysx/target/aarch64-apple-darwin/release/libmagicphysx.dylib

  # liblz4-android-x64:
  #   runs-on: ubuntu-latest
  #   timeout-minutes: 30
  #   defaults:
  #     run:
  #       working-directory: ./src/liblz4
  #   steps:
  #     - uses: actions/checkout@v3
  #       with:
  #         submodules: 'true'
  #     - run: sudo apt-get install gcc-multilib
  #     - run: rustup target add i686-linux-android
  #     - run: cargo build --target i686-linux-android --release
  #     # - uses: actions/upload-artifact@v3
  #     #   with:
  #     #     name: osx-x64
  #     #     path: ./src/libmagicphysx/target/x86_64-apple-darwin/release/libmagicphysx.dylib

  liblz4-android-arm64:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    defaults:
      run:
        working-directory: ./src/liblz4
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'true'
      - run: sudo apt-get install gcc-multilib
      - run: rustup target add aarch64-linux-android
      - run: cargo install cargo-ndk
      - run: cargo ndk -t arm64-v8a build --release
      # - uses: actions/upload-artifact@v3
      #   with:
      #     name: osx-arm64
      #     path: ./src/libmagicphysx/target/aarch64-apple-darwin/release/libmagicphysx.dylib
