name: Build-iOS-Android

# on: workflow_dispatch
# for testing
on:
  push:
    branches:
      - feature/android-ios-build

jobs:
  liblz4-ios-x64:
    runs-on: macos-latest
    timeout-minutes: 30
    defaults:
      run:
        working-directory: ./src/liblz4
    steps:
      - uses: actions/checkout@v3
      - run: rustup target add x86_64-apple-ios
      - run: cargo build --target x86_64-apple-ios --release
      # - uses: actions/upload-artifact@v3
      #   with:
      #     name: osx-x64
      #     path: ./src/libmagicphysx/target/x86_64-apple-darwin/release/libmagicphysx.dylib

  liblz4-osx-arm64:
    runs-on: macos-latest
    timeout-minutes: 30
    defaults:
      run:
        working-directory: ./src/liblz4
    steps:
      - uses: actions/checkout@v3
      - run: rustup target add aarch64-apple-ios
      - run: cargo build --target aarch64-apple-ios --release
      # - uses: actions/upload-artifact@v3
      #   with:
      #     name: osx-arm64
      #     path: ./src/libmagicphysx/target/aarch64-apple-darwin/release/libmagicphysx.dylib
