name: Build-iOS-Android

# on: workflow_dispatch
# for testing
on:
  push:
    branches:
      - feature/zstd-ios-android-build

jobs:
  liblz4-ios-x64:
    runs-on: macos-latest
    timeout-minutes: 30
    defaults:
      run:
        working-directory: ./src/liblz4
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'true'
      - run: rustup target add x86_64-apple-ios
      - run: cargo build --target x86_64-apple-ios --release

  liblz4-ios-arm64:
    runs-on: macos-latest
    timeout-minutes: 30
    defaults:
      run:
        working-directory: ./src/liblz4
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'true'
      - run: rustup target add aarch64-apple-ios
      - run: cargo build --target aarch64-apple-ios --release

  liblz4-android-arm64:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    defaults:
      run:
        working-directory: ./src/liblz4
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'true'
      - run: sudo apt-get install gcc-multilib
      - run: rustup target add aarch64-linux-android
      - run: cargo install cargo-ndk
      - run: cargo ndk -t arm64-v8a build --release

  libzstd-ios-x64:
    runs-on: macos-latest
    timeout-minutes: 30
    defaults:
      run:
        working-directory: ./src/libzstd
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'true'
      - run: rustup target add x86_64-apple-ios
      - run: cargo build --target x86_64-apple-ios --release

  libzstd-ios-arm64:
    runs-on: macos-latest
    timeout-minutes: 30
    defaults:
      run:
        working-directory: ./src/libzstd
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'true'
      - run: rustup target add aarch64-apple-ios
      - run: cargo build --target aarch64-apple-ios --release

  libzstd-android-arm64:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    defaults:
      run:
        working-directory: ./src/libzstd
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'true'
      - run: sudo apt-get install gcc-multilib
      - run: rustup target add aarch64-linux-android
      - run: cargo install cargo-ndk
      - run: cargo ndk -t arm64-v8a --bindgen build --release
