/* automatically generated by csbindgen */

#[allow(unused)]
use ::std::os::raw::*;

use super::zstd;


#[no_mangle]
pub unsafe extern "C" fn nativecompressions_ZSTD_versionNumber(

) -> c_uint
{
    zstd::ZSTD_versionNumber(

    )
}

#[no_mangle]
pub unsafe extern "C" fn nativecompressions_ZSTD_versionString(

) -> *const c_char
{
    zstd::ZSTD_versionString(

    )
}

#[no_mangle]
pub unsafe extern "C" fn nativecompressions_ZSTD_compress(
    dst: *mut c_void,
    dstCapacity: usize,
    src: *const c_void,
    srcSize: usize,
    compressionLevel: c_int
) -> usize
{
    zstd::ZSTD_compress(
        dst,
        dstCapacity,
        src,
        srcSize,
        compressionLevel
    )
}

#[no_mangle]
pub unsafe extern "C" fn nativecompressions_ZSTD_decompress(
    dst: *mut c_void,
    dstCapacity: usize,
    src: *const c_void,
    compressedSize: usize
) -> usize
{
    zstd::ZSTD_decompress(
        dst,
        dstCapacity,
        src,
        compressedSize
    )
}

#[no_mangle]
pub unsafe extern "C" fn nativecompressions_ZSTD_getFrameContentSize(
    src: *const c_void,
    srcSize: usize
) -> c_ulonglong
{
    zstd::ZSTD_getFrameContentSize(
        src,
        srcSize
    )
}

#[no_mangle]
pub unsafe extern "C" fn nativecompressions_ZSTD_getDecompressedSize(
    src: *const c_void,
    srcSize: usize
) -> c_ulonglong
{
    zstd::ZSTD_getDecompressedSize(
        src,
        srcSize
    )
}

#[no_mangle]
pub unsafe extern "C" fn nativecompressions_ZSTD_findFrameCompressedSize(
    src: *const c_void,
    srcSize: usize
) -> usize
{
    zstd::ZSTD_findFrameCompressedSize(
        src,
        srcSize
    )
}

#[no_mangle]
pub unsafe extern "C" fn nativecompressions_ZSTD_compressBound(
    srcSize: usize
) -> usize
{
    zstd::ZSTD_compressBound(
        srcSize
    )
}

#[no_mangle]
pub unsafe extern "C" fn nativecompressions_ZSTD_isError(
    code: usize
) -> c_uint
{
    zstd::ZSTD_isError(
        code
    )
}

#[no_mangle]
pub unsafe extern "C" fn nativecompressions_ZSTD_getErrorName(
    code: usize
) -> *const c_char
{
    zstd::ZSTD_getErrorName(
        code
    )
}

#[no_mangle]
pub unsafe extern "C" fn nativecompressions_ZSTD_minCLevel(

) -> c_int
{
    zstd::ZSTD_minCLevel(

    )
}

#[no_mangle]
pub unsafe extern "C" fn nativecompressions_ZSTD_maxCLevel(

) -> c_int
{
    zstd::ZSTD_maxCLevel(

    )
}

#[no_mangle]
pub unsafe extern "C" fn nativecompressions_ZSTD_defaultCLevel(

) -> c_int
{
    zstd::ZSTD_defaultCLevel(

    )
}

#[no_mangle]
pub unsafe extern "C" fn nativecompressions_ZSTD_createCCtx(

) -> *mut zstd::ZSTD_CCtx
{
    zstd::ZSTD_createCCtx(

    )
}

#[no_mangle]
pub unsafe extern "C" fn nativecompressions_ZSTD_freeCCtx(
    cctx: *mut zstd::ZSTD_CCtx
) -> usize
{
    zstd::ZSTD_freeCCtx(
        cctx
    )
}

#[no_mangle]
pub unsafe extern "C" fn nativecompressions_ZSTD_compressCCtx(
    cctx: *mut zstd::ZSTD_CCtx,
    dst: *mut c_void,
    dstCapacity: usize,
    src: *const c_void,
    srcSize: usize,
    compressionLevel: c_int
) -> usize
{
    zstd::ZSTD_compressCCtx(
        cctx,
        dst,
        dstCapacity,
        src,
        srcSize,
        compressionLevel
    )
}

#[no_mangle]
pub unsafe extern "C" fn nativecompressions_ZSTD_createDCtx(

) -> *mut zstd::ZSTD_DCtx
{
    zstd::ZSTD_createDCtx(

    )
}

#[no_mangle]
pub unsafe extern "C" fn nativecompressions_ZSTD_freeDCtx(
    dctx: *mut zstd::ZSTD_DCtx
) -> usize
{
    zstd::ZSTD_freeDCtx(
        dctx
    )
}

#[no_mangle]
pub unsafe extern "C" fn nativecompressions_ZSTD_decompressDCtx(
    dctx: *mut zstd::ZSTD_DCtx,
    dst: *mut c_void,
    dstCapacity: usize,
    src: *const c_void,
    srcSize: usize
) -> usize
{
    zstd::ZSTD_decompressDCtx(
        dctx,
        dst,
        dstCapacity,
        src,
        srcSize
    )
}

#[no_mangle]
pub unsafe extern "C" fn nativecompressions_ZSTD_cParam_getBounds(
    cParam: zstd::ZSTD_cParameter
) -> zstd::ZSTD_bounds
{
    zstd::ZSTD_cParam_getBounds(
        cParam
    )
}

#[no_mangle]
pub unsafe extern "C" fn nativecompressions_ZSTD_CCtx_setParameter(
    cctx: *mut zstd::ZSTD_CCtx,
    param: zstd::ZSTD_cParameter,
    value: c_int
) -> usize
{
    zstd::ZSTD_CCtx_setParameter(
        cctx,
        param,
        value
    )
}

#[no_mangle]
pub unsafe extern "C" fn nativecompressions_ZSTD_CCtx_setPledgedSrcSize(
    cctx: *mut zstd::ZSTD_CCtx,
    pledgedSrcSize: c_ulonglong
) -> usize
{
    zstd::ZSTD_CCtx_setPledgedSrcSize(
        cctx,
        pledgedSrcSize
    )
}

#[no_mangle]
pub unsafe extern "C" fn nativecompressions_ZSTD_CCtx_reset(
    cctx: *mut zstd::ZSTD_CCtx,
    reset: zstd::ZSTD_ResetDirective
) -> usize
{
    zstd::ZSTD_CCtx_reset(
        cctx,
        reset
    )
}

#[no_mangle]
pub unsafe extern "C" fn nativecompressions_ZSTD_compress2(
    cctx: *mut zstd::ZSTD_CCtx,
    dst: *mut c_void,
    dstCapacity: usize,
    src: *const c_void,
    srcSize: usize
) -> usize
{
    zstd::ZSTD_compress2(
        cctx,
        dst,
        dstCapacity,
        src,
        srcSize
    )
}

#[no_mangle]
pub unsafe extern "C" fn nativecompressions_ZSTD_dParam_getBounds(
    dParam: zstd::ZSTD_dParameter
) -> zstd::ZSTD_bounds
{
    zstd::ZSTD_dParam_getBounds(
        dParam
    )
}

#[no_mangle]
pub unsafe extern "C" fn nativecompressions_ZSTD_DCtx_setParameter(
    dctx: *mut zstd::ZSTD_DCtx,
    param: zstd::ZSTD_dParameter,
    value: c_int
) -> usize
{
    zstd::ZSTD_DCtx_setParameter(
        dctx,
        param,
        value
    )
}

#[no_mangle]
pub unsafe extern "C" fn nativecompressions_ZSTD_DCtx_reset(
    dctx: *mut zstd::ZSTD_DCtx,
    reset: zstd::ZSTD_ResetDirective
) -> usize
{
    zstd::ZSTD_DCtx_reset(
        dctx,
        reset
    )
}

#[no_mangle]
pub unsafe extern "C" fn nativecompressions_ZSTD_createCStream(

) -> *mut zstd::ZSTD_CStream
{
    zstd::ZSTD_createCStream(

    )
}

#[no_mangle]
pub unsafe extern "C" fn nativecompressions_ZSTD_freeCStream(
    zcs: *mut zstd::ZSTD_CStream
) -> usize
{
    zstd::ZSTD_freeCStream(
        zcs
    )
}

#[no_mangle]
pub unsafe extern "C" fn nativecompressions_ZSTD_compressStream2(
    cctx: *mut zstd::ZSTD_CCtx,
    output: *mut zstd::ZSTD_outBuffer,
    input: *mut zstd::ZSTD_inBuffer,
    endOp: zstd::ZSTD_EndDirective
) -> usize
{
    zstd::ZSTD_compressStream2(
        cctx,
        output,
        input,
        endOp
    )
}

#[no_mangle]
pub unsafe extern "C" fn nativecompressions_ZSTD_CStreamInSize(

) -> usize
{
    zstd::ZSTD_CStreamInSize(

    )
}

#[no_mangle]
pub unsafe extern "C" fn nativecompressions_ZSTD_CStreamOutSize(

) -> usize
{
    zstd::ZSTD_CStreamOutSize(

    )
}

#[no_mangle]
pub unsafe extern "C" fn nativecompressions_ZSTD_initCStream(
    zcs: *mut zstd::ZSTD_CStream,
    compressionLevel: c_int
) -> usize
{
    zstd::ZSTD_initCStream(
        zcs,
        compressionLevel
    )
}

#[no_mangle]
pub unsafe extern "C" fn nativecompressions_ZSTD_compressStream(
    zcs: *mut zstd::ZSTD_CStream,
    output: *mut zstd::ZSTD_outBuffer,
    input: *mut zstd::ZSTD_inBuffer
) -> usize
{
    zstd::ZSTD_compressStream(
        zcs,
        output,
        input
    )
}

#[no_mangle]
pub unsafe extern "C" fn nativecompressions_ZSTD_flushStream(
    zcs: *mut zstd::ZSTD_CStream,
    output: *mut zstd::ZSTD_outBuffer
) -> usize
{
    zstd::ZSTD_flushStream(
        zcs,
        output
    )
}

#[no_mangle]
pub unsafe extern "C" fn nativecompressions_ZSTD_endStream(
    zcs: *mut zstd::ZSTD_CStream,
    output: *mut zstd::ZSTD_outBuffer
) -> usize
{
    zstd::ZSTD_endStream(
        zcs,
        output
    )
}

#[no_mangle]
pub unsafe extern "C" fn nativecompressions_ZSTD_createDStream(

) -> *mut zstd::ZSTD_DStream
{
    zstd::ZSTD_createDStream(

    )
}

#[no_mangle]
pub unsafe extern "C" fn nativecompressions_ZSTD_freeDStream(
    zds: *mut zstd::ZSTD_DStream
) -> usize
{
    zstd::ZSTD_freeDStream(
        zds
    )
}

#[no_mangle]
pub unsafe extern "C" fn nativecompressions_ZSTD_initDStream(
    zds: *mut zstd::ZSTD_DStream
) -> usize
{
    zstd::ZSTD_initDStream(
        zds
    )
}

#[no_mangle]
pub unsafe extern "C" fn nativecompressions_ZSTD_decompressStream(
    zds: *mut zstd::ZSTD_DStream,
    output: *mut zstd::ZSTD_outBuffer,
    input: *mut zstd::ZSTD_inBuffer
) -> usize
{
    zstd::ZSTD_decompressStream(
        zds,
        output,
        input
    )
}

#[no_mangle]
pub unsafe extern "C" fn nativecompressions_ZSTD_DStreamInSize(

) -> usize
{
    zstd::ZSTD_DStreamInSize(

    )
}

#[no_mangle]
pub unsafe extern "C" fn nativecompressions_ZSTD_DStreamOutSize(

) -> usize
{
    zstd::ZSTD_DStreamOutSize(

    )
}

#[no_mangle]
pub unsafe extern "C" fn nativecompressions_ZSTD_compress_usingDict(
    ctx: *mut zstd::ZSTD_CCtx,
    dst: *mut c_void,
    dstCapacity: usize,
    src: *const c_void,
    srcSize: usize,
    dict: *const c_void,
    dictSize: usize,
    compressionLevel: c_int
) -> usize
{
    zstd::ZSTD_compress_usingDict(
        ctx,
        dst,
        dstCapacity,
        src,
        srcSize,
        dict,
        dictSize,
        compressionLevel
    )
}

#[no_mangle]
pub unsafe extern "C" fn nativecompressions_ZSTD_decompress_usingDict(
    dctx: *mut zstd::ZSTD_DCtx,
    dst: *mut c_void,
    dstCapacity: usize,
    src: *const c_void,
    srcSize: usize,
    dict: *const c_void,
    dictSize: usize
) -> usize
{
    zstd::ZSTD_decompress_usingDict(
        dctx,
        dst,
        dstCapacity,
        src,
        srcSize,
        dict,
        dictSize
    )
}

#[no_mangle]
pub unsafe extern "C" fn nativecompressions_ZSTD_createCDict(
    dictBuffer: *const c_void,
    dictSize: usize,
    compressionLevel: c_int
) -> *mut zstd::ZSTD_CDict
{
    zstd::ZSTD_createCDict(
        dictBuffer,
        dictSize,
        compressionLevel
    )
}

#[no_mangle]
pub unsafe extern "C" fn nativecompressions_ZSTD_freeCDict(
    CDict: *mut zstd::ZSTD_CDict
) -> usize
{
    zstd::ZSTD_freeCDict(
        CDict
    )
}

#[no_mangle]
pub unsafe extern "C" fn nativecompressions_ZSTD_compress_usingCDict(
    cctx: *mut zstd::ZSTD_CCtx,
    dst: *mut c_void,
    dstCapacity: usize,
    src: *const c_void,
    srcSize: usize,
    cdict: *const zstd::ZSTD_CDict
) -> usize
{
    zstd::ZSTD_compress_usingCDict(
        cctx,
        dst,
        dstCapacity,
        src,
        srcSize,
        cdict
    )
}

#[no_mangle]
pub unsafe extern "C" fn nativecompressions_ZSTD_createDDict(
    dictBuffer: *const c_void,
    dictSize: usize
) -> *mut zstd::ZSTD_DDict
{
    zstd::ZSTD_createDDict(
        dictBuffer,
        dictSize
    )
}

#[no_mangle]
pub unsafe extern "C" fn nativecompressions_ZSTD_freeDDict(
    ddict: *mut zstd::ZSTD_DDict
) -> usize
{
    zstd::ZSTD_freeDDict(
        ddict
    )
}

#[no_mangle]
pub unsafe extern "C" fn nativecompressions_ZSTD_decompress_usingDDict(
    dctx: *mut zstd::ZSTD_DCtx,
    dst: *mut c_void,
    dstCapacity: usize,
    src: *const c_void,
    srcSize: usize,
    ddict: *const zstd::ZSTD_DDict
) -> usize
{
    zstd::ZSTD_decompress_usingDDict(
        dctx,
        dst,
        dstCapacity,
        src,
        srcSize,
        ddict
    )
}

#[no_mangle]
pub unsafe extern "C" fn nativecompressions_ZSTD_getDictID_fromDict(
    dict: *const c_void,
    dictSize: usize
) -> c_uint
{
    zstd::ZSTD_getDictID_fromDict(
        dict,
        dictSize
    )
}

#[no_mangle]
pub unsafe extern "C" fn nativecompressions_ZSTD_getDictID_fromCDict(
    cdict: *const zstd::ZSTD_CDict
) -> c_uint
{
    zstd::ZSTD_getDictID_fromCDict(
        cdict
    )
}

#[no_mangle]
pub unsafe extern "C" fn nativecompressions_ZSTD_getDictID_fromDDict(
    ddict: *const zstd::ZSTD_DDict
) -> c_uint
{
    zstd::ZSTD_getDictID_fromDDict(
        ddict
    )
}

#[no_mangle]
pub unsafe extern "C" fn nativecompressions_ZSTD_getDictID_fromFrame(
    src: *const c_void,
    srcSize: usize
) -> c_uint
{
    zstd::ZSTD_getDictID_fromFrame(
        src,
        srcSize
    )
}

#[no_mangle]
pub unsafe extern "C" fn nativecompressions_ZSTD_CCtx_loadDictionary(
    cctx: *mut zstd::ZSTD_CCtx,
    dict: *const c_void,
    dictSize: usize
) -> usize
{
    zstd::ZSTD_CCtx_loadDictionary(
        cctx,
        dict,
        dictSize
    )
}

#[no_mangle]
pub unsafe extern "C" fn nativecompressions_ZSTD_CCtx_refCDict(
    cctx: *mut zstd::ZSTD_CCtx,
    cdict: *const zstd::ZSTD_CDict
) -> usize
{
    zstd::ZSTD_CCtx_refCDict(
        cctx,
        cdict
    )
}

#[no_mangle]
pub unsafe extern "C" fn nativecompressions_ZSTD_CCtx_refPrefix(
    cctx: *mut zstd::ZSTD_CCtx,
    prefix: *const c_void,
    prefixSize: usize
) -> usize
{
    zstd::ZSTD_CCtx_refPrefix(
        cctx,
        prefix,
        prefixSize
    )
}

#[no_mangle]
pub unsafe extern "C" fn nativecompressions_ZSTD_DCtx_loadDictionary(
    dctx: *mut zstd::ZSTD_DCtx,
    dict: *const c_void,
    dictSize: usize
) -> usize
{
    zstd::ZSTD_DCtx_loadDictionary(
        dctx,
        dict,
        dictSize
    )
}

#[no_mangle]
pub unsafe extern "C" fn nativecompressions_ZSTD_DCtx_refDDict(
    dctx: *mut zstd::ZSTD_DCtx,
    ddict: *const zstd::ZSTD_DDict
) -> usize
{
    zstd::ZSTD_DCtx_refDDict(
        dctx,
        ddict
    )
}

#[no_mangle]
pub unsafe extern "C" fn nativecompressions_ZSTD_DCtx_refPrefix(
    dctx: *mut zstd::ZSTD_DCtx,
    prefix: *const c_void,
    prefixSize: usize
) -> usize
{
    zstd::ZSTD_DCtx_refPrefix(
        dctx,
        prefix,
        prefixSize
    )
}

#[no_mangle]
pub unsafe extern "C" fn nativecompressions_ZSTD_sizeof_CCtx(
    cctx: *const zstd::ZSTD_CCtx
) -> usize
{
    zstd::ZSTD_sizeof_CCtx(
        cctx
    )
}

#[no_mangle]
pub unsafe extern "C" fn nativecompressions_ZSTD_sizeof_DCtx(
    dctx: *const zstd::ZSTD_DCtx
) -> usize
{
    zstd::ZSTD_sizeof_DCtx(
        dctx
    )
}

#[no_mangle]
pub unsafe extern "C" fn nativecompressions_ZSTD_sizeof_CStream(
    zcs: *const zstd::ZSTD_CStream
) -> usize
{
    zstd::ZSTD_sizeof_CStream(
        zcs
    )
}

#[no_mangle]
pub unsafe extern "C" fn nativecompressions_ZSTD_sizeof_DStream(
    zds: *const zstd::ZSTD_DStream
) -> usize
{
    zstd::ZSTD_sizeof_DStream(
        zds
    )
}

#[no_mangle]
pub unsafe extern "C" fn nativecompressions_ZSTD_sizeof_CDict(
    cdict: *const zstd::ZSTD_CDict
) -> usize
{
    zstd::ZSTD_sizeof_CDict(
        cdict
    )
}

#[no_mangle]
pub unsafe extern "C" fn nativecompressions_ZSTD_sizeof_DDict(
    ddict: *const zstd::ZSTD_DDict
) -> usize
{
    zstd::ZSTD_sizeof_DDict(
        ddict
    )
}

    